### ISSUE TITLE
M3: Remote Attestation Registry Module

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE-node-pre2.0.0#1]
The `ra-registry` module serves the purpose of maintaining a register of remote attested substraTEE-worker enclaves.

## `register(signing_pubkey, call_encryption_pubkey, ra_quote_from_IAS)`
This function is called by the worker when the enclave is set up or after each SW update modifying the MRENCLAVE

The module has to parse the ra_quote and make sure it is valid by
* validating IAS signature
* validating quote: acceptance should be configurable. In the end we only allow fully patched SGX running in release mode, but for debuging we'll allow debug mode as well and maybe even unpatched SGX
* dispatches an Event `WorkerRegistered(signing_key, encryption_key, 
* counterpart supplying the quote: https://github.com/scs/substraTEE-worker/issues/18

## `revoke(signing_key)`
* TBD

## registration lifetime
RA quotes are valid for a configurable amount of blocks. Cleaning up however is a task that demands running through the entire registry, which isn't something we should do in runtime for performance reasons. We might want to use a [substrate-offchain-worker](https://github.com/paritytech/substrate/tree/master/core/offchain) for this. Because such a worker may take as long as it takes to return moreover it can access chain state directly. Another option is to use a substaTEE-worker for this, but accessing chain state is more difficult. 

## open questions
* should we also register information about where to reach a worker (IP or Kademlia addr). 
  *Answer*: Probably we can let workers promote their services themselves. users then just verify their keys using the ra_registry
* how can we convince the user that ONLY the correct wasm is running on that worker enclave?
  *Answer* This is up to the enclave TCB to ensure: The user has to supply the hash of the wasm code with every call
* how do we add/revoke RA services keys (adding new manufacturers/attestation services keys) -> srml-democracy?

Hints:
* check out how sawtooth verifies IAS quotes: https://github.com/hyperledger-labs/private-data-objects/blob/fce68acd5e51043b54ce2fdf7509e568f5402552/sawtooth/common/pdo_signing.py#L401
* it might be difficult to parse an IAS quote in a runtime module, as no string tools are included in rstd. We might need to implement our own host call for this (similar to blake2_256, which is not executed in wasm but a host-provided call)

**Comment by electronix** [comment]
Additional function:

## list_enclaves()
which returns a list of all registered enclaves, incl. their address

**Comment by brenzi** [comment]
We will actually need the URL for the worker service to be in the registry as well. 
1. A requester looks up the enclave registry where he finds the worker enclave's signing pubkey along with the workers URL.
1. The requester then requests the shielding key from the worker via WS (currently in M2 this key is hard-coded). This request must include a nonce to avoid replay. 
1. The worker returns the shielding pubkey and the nonce, signed by the enclaves signing pubkey
1. the requester validates the signature and can then encrypt his request tx payload with the newly obtained shielding key
1. After invocation, the client verifies the counter has been updated by requesting the counter state from the worker (I suggest to fix the following at the same time: https://github.com/scs/substraTEE-worker/issues/19)

**Comment by electronix** [comment]
Implemented partially with M4 (https://github.com/scs/substraTEE-node/releases/tag/M4).

The exchange of the shielding key does not implement a nonce and the keys are exchanged over a TLS connection without additional encryption.
