### ISSUE TITLE
drop host_calls to be Parachain compatible

### ISSUE THREAD

**Issue by clangenb** [scs/substraTEE-node-pre2.0.0#17]
For a node to be deployed as a Polkadot Parachain it must **not** feature custom `host_calls`. Therefore, we need to do the verification of the remote attestation report in the runtime.

Following issues will need to be addressed:
* Remove string parsing, i.e., serde dependencies -> do byte comparision instead
* Remove itertools dependency -> implement it ourselves.
* Remove chrono dependency -> use substrate timestamp module
* Remove base64 dependency -> implement decoding ourselves
* webpki would be `no_std` compatible. But check the wasm size, which might be big due to all the crypto primitives introduced.

**Comment by brenzi** [comment]
I think we really shouldn't drag webpki into the runtime wasm. Better to PR support for the needed crypto primitives in sr_io upstream

**Comment by brenzi** [comment]
phala has ported webpki and ring to be compiled in wasm runtime.
I've ported our host-calls into the runtime:
https://github.com/scs/pallet-substratee-registry/tree/nohostcalls

however, right now only parsing, no verification yet. WIP

**Comment by brenzi** [comment]
we can now verify CA and signature.
What doesn't work yet is ECDSA signature verification with ring. See:
https://github.com/briansmith/ring/issues/967

**Comment by brenzi** [comment]
works. released as v0.6.0
will need to be tested against a worker, once we migrated that to v2.0.0
