### ISSUE TITLE
upgrade to recent upstream master

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE-node-pre2.0.0#9]
I'm currently upgrading to substrate master 

work started on branch [brenzi-upstream-sync](https://github.com/scs/substraTEE-node/tree/brenzi-upstream-sync)

code adapted. stuck at 
```
error: duplicate lang item in crate `sr_tee_io`: `panic_impl`.
  |
  = note: first defined in crate `sr_io`.

error: duplicate lang item in crate `sr_tee_io`: `oom`.
  |
  = note: first defined in crate `sr_io`.

```

caused by: https://github.com/paritytech/substrate/issues/3271

**Comment by clangenb** [comment]
Supports now : https://github.com/paritytech/substrate/commit/f17d023bbe179f15678ac9989f471c9b18917e17
